### ISSUE TITLE
Allow multiple independent conclusions for checks.

### ISSUE THREAD

**Issue by lhunath** [dflydev/check-runs-action#21]
Currently, we can conclude multiple checks at once using:
```
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: success
```
And we can even specify the checks that this should apply to, using JSON:
```
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checks: [ { "id": "check-1", name: "Check 1" }, { "id": "check-2", name: "Check 2" } ]
          conclusion: success
```
But it is impossible to set individual conclusions for the different checks. It seems it would be simple enough:
```
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checks: [ { "id": "check-1", name: "Check 1", conclusion: "success" }, { "id": "check-2", name: "Check 2", conclusion: "failure", output: { summary: "Meep" } } ]
```

But this is not currently permitted; and we get the odd message:
```
Error: invalid format for 'checks: SyntaxError: Unexpected token c in JSON at position 46
```

This forces us to duplicate the job countless times for each individual check, which is sloppy and a maintenance pain.

Ideally, the `checks` input would accept the full scope of a check's definition, as specified in https://github.com/dflydev/check-runs-action/blob/master/src/namespaces/Inputs.ts#L28-L42
